# Generated by Django 4.2.14 on 2024-07-12 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0002_alter_savingsgoal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='current_amount',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='name',
            field=models.CharField(default='car', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('completed', 'Completed'), ('failed', 'Failed')], default='live', max_length=10),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
