# Generated by Django 4.2.14 on 2024-07-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_type_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Debit', 'Credit')], default='debit', max_length=10),
        ),
    ]
